### ISSUE TITLE
Inconsistent repository description

### ISSUE THREAD

**Issue by CyberShadow** [acama/xrop#11]
The repository description says:

> Tool to generate ROP gadgets for ARM, AARCH64, x86, MIPS, PPC, RISCV, SH4 and SPARC

But the README says:

> currently supports generating ROP gadgets for x86, x86_64, arm, ppc and mips

So, RISCV, SH4 and SPARC don't seem to actually be supported.

**Comment by sheepNo** [comment]
Why was this issue closed ? I wanted to use this tool to study ROP on RISCV but it seems that this is still the case. On top of that it looks like you already do some things for riscv but you just don't take riscv as an argument in the command line ?
